name: api.invidious.io CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    name: "build - crystal: ${{ matrix.crystal }}, stable: ${{ matrix.stable }}"

    continue-on-error: ${{ !matrix.stable }}

    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        crystal:
          - 1.0.0
          - 1.6.0
          - 1.9.2
        include:
          - crystal: nightly
            stable: false

    steps:
      - uses: actions/checkout@v3

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1.8.0
        with:
          crystal: ${{ matrix.crystal }}

      - name: Cache Shards
        uses: actions/cache@v3
        with:
          path: ./lib
          key: shards-${{ hashFiles('shard.lock') }}

      - name: Install Shards
        run: |
          if ! shards check; then
            shards install
          fi

      - name: Run lint
        run: |
          if ! crystal tool format --check; then
            crystal tool format
            git diff
            exit 1
          fi

      - name: Build
        run: crystal build --warnings all --error-on-warnings --error-trace src/instances.cr

  build-docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker
        run: docker-compose up -d

      - name: Test Docker
        run: curl -Isf http://localhost:3000
